import DashboardToggleProvider from "@/providers/dashboardToggleProvider";
import NextAuthSessionProvider from "@/providers/sessionProvider";
import { DM_Sans } from "next/font/google";
import "./globals.css";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  display:"swap",

});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} antialiased`}
      >
        <DashboardToggleProvider>
          <NextAuthSessionProvider>
            {children}
          </NextAuthSessionProvider>
        </DashboardToggleProvider>
      </body>
    </html>
  );
}
